#!/bin/sh

if [ "$ACTION" = "ifup" -a "$INTERFACE" = "lan" ]; then
	/etc/init.d/http_status_stat is_enabled
	if [ $? -eq 1 ]; then
		logger -t "hotplug.d" "http_stat_proxy refresh_lan"
		/etc/init.d/http_status_stat refresh_lan
	fi
fi
