#!/bin/sh /etc/rc.common

START=99

set_switch_off="uci set rule_mgr.switch.ad_filter_center=0"
set_switch_on="uci set rule_mgr.switch.ad_filter_center=1"
set_switch_commit="uci commit rule_mgr"

export EXTRA_COMMANDS=" on off "
export EXTRA_HELP="	on	Switch to the start state and start
	off	Switch to the stop state and stop"

start() {
    switch_ad_filter=`uci get rule_mgr.switch.ad_filter_center 2>/dev/null`
    if [ $switch_ad_filter -ne "1" ]; then
        #if not enabled, just exit
        return 0
    fi

    #avoid to hold start procedure, use nohup
    nohup /usr/sbin/ad_filter.sh >/dev/null 2>&1 &

    return 0
}

stop() {
    # disable ad_filter switch
    echo "0" > /proc/sys/net/ipv4/http_ad_filter_switch

    /etc/init.d/rule_mgr status
    if [ $? -eq "0" ]; then
        echo "ad_filter try to close rule_mgr."
        /usr/sbin/ad_filter_client --clean
        /etc/init.d/rule_mgr stop
    fi

    return 0
}


off(){
    $set_switch_off >/dev/null 2>&1
    $set_switch_commit >/dev/null 2>&1
    stop
    return $?
}

on(){
    $set_switch_on >/dev/null 2>&1
    $set_switch_commit >/dev/null 2>&1

    start
    return $?
}

