#!/bin/sh /etc/rc.common

START=99

set_switch_on="uci set http_timeout.settings.enabled=1"
set_switch_off="uci set http_timeout.settings.enabled=0"
set_switch_commit="uci commit http_timeout"
HTTP_TIMEOUT_SH="/usr/sbin/http_timeout.sh"

export EXTRA_COMMANDS=" on off log_stat"
export EXTRA_HELP="	on	Switch to the start state and start
	off	Switch to the stop state and stop
	log_stat	log stat of rtt"

log_stat() {
    rtt_stat_file="/proc/http_timeout/rtt_stat"
    if [ -f $rtt_stat_file ]; then
        line=`cat $rtt_stat_file`
        v1=`echo $line | awk '{print $1}'`
        v2=`echo $line | awk '{print $2}'`
        v3=`echo $line | awk '{print $3}'`
        v4=`echo $line | awk '{print $4}'`
        logger stat_points_privacy http_rttl=$v1,$v2,$v3,$v4
        echo "0" > $rtt_stat_file
    fi
}

start() {
    switch=`uci get http_timeout.settings.enabled -q`
    if [ $switch -ne "1" ]; then
        #if not enabled, just exit
        return 0
    fi

    $HTTP_TIMEOUT_SH on
    return 0
}

stop() {
    $HTTP_TIMEOUT_SH off
    return 0
}

off() {
    $set_switch_off >/dev/null 2>&1
    $set_switch_commit >/dev/null 2>&1
    stop
    return $?
}

on() {
    $set_switch_on >/dev/null 2>&1
    $set_switch_commit >/dev/null 2>&1

    start
    return $?
}

