#!/bin/sh /etc/rc.common

START=99

set_switch_off="uci set rule_mgr.switch.security_center=0"
set_switch_on="uci set rule_mgr.switch.security_center=1"
set_switch_commit="uci commit"

export EXTRA_COMMANDS=" on off "
export EXTRA_HELP="	on	Switch to the start state and start
	off	Switch to the stop state and stop"

start() {
    switch_security=`uci get rule_mgr.switch.security_center 2>/dev/null`
    if [ $switch_security -ne "1" ]; then
        #if not enabled, just exit
        return 0
    fi

    #avoid to hold start procedure, use nohup
    nohup /usr/sbin/sec_clt.sh >/dev/null 2>&1 &

	return 0
}

stop() {
    #clear security rules 1stly
    /etc/init.d/rule_mgr status
    if [ $? -eq "0" ]; then
        echo "security-clt try to close rule_mgr."
        /usr/sbin/sec_clt clean security
	    /etc/init.d/rule_mgr stop
    fi

    return 0
}


off(){
    $set_switch_off >/dev/null 2>&1
    $set_switch_commit >/dev/null 2>&1
    stop
    return $?
}

on(){
    $set_switch_on >/dev/null 2>&1
    $set_switch_commit >/dev/null 2>&1

    start
    return $?
}

