#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99

start() {

        should_usbreset=`cat /proc/xiaoqiang/usbreset`
        if [ "$should_usbreset" != "1" ]
        then
                return 0
        fi

	echo "0" > /sys/bus/usb/devices/usb1/authorized
	echo "1" > /sys/bus/usb/devices/usb1/authorized

	echo "0" > /sys/bus/usb/devices/usb2/authorized
	echo "1" > /sys/bus/usb/devices/usb2/authorized

}

