#!/bin/sh

usage() {
        echo "flash_led 1/2/3"
	echo "[1] = 29;//led red"
	echo "[2] = 26;//led yellow"
	echo "[3] = 24;//led blue"
}


case $1 in
        1)
	gpio 2 1
	gpio 3 1
	gpio l 29 3 3 1 0 1
        ;;
        2)
	gpio 1 1
	gpio 3 1
	gpio l 26 3 3 1 0 1
        ;;
        3)
	gpio 1 1
	gpio 2 1
	gpio l 24 3 3 1 0 1
        ;;
        *)
        usage
        ;;
esac