#!/bin/sh /etc/rc.common

START=99

set_switch_off="uci set rule_mgr.switch.content_filter_center=0"
set_switch_on="uci set rule_mgr.switch.content_filter_center=1"
set_switch_commit="uci commit rule_mgr"

export EXTRA_COMMANDS=" on off "
export EXTRA_HELP="	on	Switch to the start state and start
	off	Switch to the stop state and stop"

clean_kernel_rule()
{
    # disable content_filter switch
    # echo "0" > /proc/sys/net/ipv4/http_content_filter_switch

    /etc/init.d/rule_mgr status
    if [ $? -eq "0" ]; then
        echo "content_filter try to close rule_mgr."
        /usr/sbin/content_filter_client --clean
        /etc/init.d/rule_mgr stop
    fi
}

cfg_name=toolbar
dest_port=80
local_port=8197

start() {
    switch_content_filter=`uci get rule_mgr.switch.content_filter_center -q`
    if [ $switch_content_filter -ne "1" ]; then
        #if not enabled, just exit
        return 0
    fi

    #avoid to hold start procedure, use nohup
    nohup /usr/sbin/content_filter.sh 0 start >/dev/null 2>&1 &

    return 0
}

stop() {
    # clean_kernel_rule # currently not used

    #avoid to hold start procedure, use nohup
    nohup /usr/sbin/content_filter.sh 0 stop >/dev/null 2>&1 &
    return 0
}

off(){
    $set_switch_off >/dev/null 2>&1
    $set_switch_commit >/dev/null 2>&1
    ipset_redirect.sh destroy $cfg_name $dest_port $local_port
    stop
    return $?
}

on(){
    $set_switch_on >/dev/null 2>&1
    $set_switch_commit >/dev/null 2>&1
    ipset_redirect.sh create $cfg_name $dest_port $local_port
    start
    return $?
}

