#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

#01 is fstab
START=02

start() {
	[ -f /etc/syslog-ng.conf ] || return 1

	echo -1000 > /proc/$$/oom_score_adj
	service_start /usr/sbin/syslog-ng
	return $?
}

stop() {
	service_stop /usr/sbin/syslog-ng
}

reload() {
	service_reload /usr/sbin/syslog-ng
}
